### ISSUE TITLE
docker compose script mounts home directory as a volume

### ISSUE THREAD

**Issue by CluEleSsUK** [consensus-shipyard/ipc-dx-docker#1]
[here](https://github.com/consensus-shipyard/ipc-dx-docker/blob/039cdadb0ed2febe8684cc8dd3374908b081e21d/docker-compose.yaml#L78) in the docker-compose config, the user's home directory is mounted to the docker container which is probably a bad idea for a lot of reasons!
Should either be `~/.ipc`, or preferably a local dir that's in the .gitignore

**Comment by hammertoe** [comment]
Thanks for catching this, it was already updated in one location, but looks like I missed one. Fixed now!
